from zeppelin
run pip3 install jupyter
run git clone https://github.com/MrXu/transfer-learning-with-gluon.git
run mkdir transfer-learning-with-gluon/checkpoints
cmd jupyter notebook --ip=0.0.0.0 --NotebookApp.token='' --allow-root --debug
